### ISSUE TITLE
效果达不到论文上的

### ISSUE THREAD

**Issue by ChenCherry** [Kali-Hac/TranSG#6]
OMP: Info #254:KMP_AFFINITY: pid 8719 tid 8801 thread 63 bound to os proc set 15
OMP: Info #254: KMP AFFINITY: pid 8719 tid 8802 thread 64 bound to 0s proc set 0
[Evaluationon BIWIStill]mAP:0.2930|R1:0.6621-R5:0.8574- R10: 0.8965
(TranSGtf21)asus@asus-System-Product-Name:~/daima/TranSG-main$

**Comment by Kali-Hac** [comment]
Hi, thanks for your comment. In our paper, we reported the average performance of our approach on all datasets. Due to the random initialization of model parameters (causing a different starting point in EM learning process), there may be a slight performance variation, which was also analyzed in our appendices. 

You may run this model more times and adopt the average performance result. Hope it can help, thanks.

**Comment by ChenCherry** [comment]
好的
